14-feature-user-management
Segelzwerg/Rechnung pull request #265
Opened 2024-12-10 10:20 UTC by Segelzwerg

2024-12-18 00:08 UTC, Segelzwerg commented on invoice/forms.py
> +        fields = ['first_name', 'last_name', 'email', 'vendor']
This will actually display all vendors. However, we want to limit it to the vendors of the user.

2024-12-18 12:04 UTC, Segelzwerg commented on invoice/views.py
> +        next_url = reverse('customer-update', args=[self.kwargs['pk']])
We need to check if something can be injected.

2024-12-18 12:21 UTC, Segelzwerg commented on invoice/forms.py
> +        fields = ['first_name', 'last_name', 'email', 'vendor']
Fixed by queryset overwrite in views.

2025-01-27 23:26 UTC, iTitus requested changes

2025-01-27 23:26 UTC, iTitus commented on invoice/views.py
> +class CustomerUpdateView(OwnMixin, UpdateView):
On the other views you did it like this:
```suggestion
class CustomerUpdateView(OwnMixin, SuccessMessageMixin, UpdateView):
```
Intended?

2025-02-01 13:43 UTC, merged